version: '3.0'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=saPassw@rd
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - /home/gabriel/dados:/var/opt/mssql/data